In [1]:
import tensorflow as tf 

/home/frei/dev/anaconda/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [33]:
g = tf.Graph()

In [34]:
# init graph 
with g.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=(None), name='x')
    w = tf.Variable(2.0, name='x')
    b = tf.Variable(0.7, name='bias')
    
    z = w*x + b
    
    init = tf.global_variables_initializer()
    
# compile graph 
with tf.Session(graph=g) as sess:
    sess.run(init)
    for t in [1.0, 0.6, -1.8]:
        print('x={:>4}  -->  z={:>4.1f}'.format(t, sess.run(z, feed_dict={x:t})))
    print(sess.run(z, feed_dict={x:[1.0, 2.0 , 3.0]}))

x= 1.0  -->  z= 2.7
x= 0.6  -->  z= 1.9
x=-1.8  -->  z=-2.9
[2.7 4.7 6.7]


In [36]:
import tensorflow as tf 
import numpy as np 

In [44]:

g = tf.Graph()
with g.as_default():
    x = tf.placeholder(dtype=tf.float32, shape=(None, 2, 3), name='input_x')
    x2 = tf.reshape(x, shape=(-1, 6), name='x2')
    xsum = tf.reduce_sum(x2, axis=0, name='col_sum')
    xmean = tf.reduce_mean(x2, axis=0, name='col_mean')

with tf.Session(graph=g) as sess:
    x_array = np.arange(18).reshape(3, 2, 3)
    
    print('input shape: ', x_array.shape)
    print('reshaped: \n', sess.run(x2, feed_dict={x: x_array}))
    print('col sums: ', sess.run(xsum, feed_dict={x: x_array}))
    print('col means: ', sess.run(xmean, feed_dict={x: x_array}))
    

input shape:  (3, 2, 3)
reshaped: 
 [[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]]
col sums:  [18. 21. 24. 27. 30. 33.]
col means:  [ 6.  7.  8.  9. 10. 11.]
