In [37]:
import pandas as pd
import numpy as np
import seaborn as sns
from scipy import stats
from statsmodels.sandbox.stats.multicomp import multipletests 
import itertools
%matplotlib inline

In [12]:
df = pd.read_csv('./AUCs.txt', '\t')

In [32]:
wilcoxon_p = []
clf1, clf2, clf3, clf4 = df.iloc[:, 1], df.iloc[:, 2], df.iloc[:, 3], df.iloc[:, 4]
for samples in itertools.combinations([clf1, clf2, clf3, clf4], 2):
    print(samples[0].name, samples[1].name, stats.wilcoxon(samples[0], samples[1])[1])
    wilcoxon_p.append(stats.wilcoxon(samples[0], samples[1])[1])

C4.5 C4.5+m 0.0107571331198
C4.5 C4.5+cf 0.861262330095
C4.5 C4.5+m+cf 0.0159064441017
C4.5+m C4.5+cf 0.0463327297934
C4.5+m C4.5+m+cf 0.327825675845
C4.5+cf C4.5+m+cf 0.0229090993544


In [33]:
df.mean(0)

C4.5         0.804929
C4.5+m       0.820429
C4.5+cf      0.808786
C4.5+m+cf    0.827214
dtype: float64

In [40]:
# поправка Холма
reject, p_corrected, a1, a2 = multipletests(wilcoxon_p, 
                                            alpha = 0.05, 
                                            method = 'holm') 
reject

array([False, False, False, False, False, False], dtype=bool)

In [42]:
# поправка Холма: неверно, так как выборки зависимые!
reject, p_corrected, a1, a2 = multipletests(wilcoxon_p, 
                                            alpha = 0.05, 
                                            method = 'fdr_bh') 
reject, p_corrected

(array([ True, False,  True, False, False,  True], dtype=bool),
 array([ 0.0458182 ,  0.86126233,  0.0458182 ,  0.06949909,  0.39339081,
         0.0458182 ]))